apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
  labels:
    app: currency-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: app
        image: artemdevopscom/currency-converter:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: APP_ENV
          value: "dev"
        - name: GUNICORN_WORKERS
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
