services:
  currency-converter:
    image: ${DOCKER_IMAGE:-artemdevopscom/currency-converter}:${IMAGE_TAG:-latest}
    container_name: currency-converter
    ports:
      - "5000:5000"
    restart: unless-stopped
    mem_limit: 256m
    cpus: '0.5'
    environment:
      - GUNICORN_WORKERS=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"    