apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: artemdevopscom/currency-converter:0b3a5f29f4d5838d99da1b94f6a0a0ad7b0e45a5
        env:
        - name: APP_ENV
          value: "development"
        - name: GUNICORN_WORKERS
          value: "1"
