apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: artemdevopscom/currency-converter:2ec35f591cd86c55cf9ae3ce71a4117783d05004
        env:
        - name: APP_ENV
          value: "development"
        - name: GUNICORN_WORKERS
          value: "1"
