apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app
        image: artemdevopscom/currency-converter:latest
        env:
        - name: APP_ENV
          value: "production"
        - name: GUNICORN_WORKERS
          value: "4"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
